### ISSUE TITLE
Provide Drupal or other settings for redis

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-redis#2]
On Twitter you mentioned the idea of providing Drupal settings.

It would be possible for the post_install_actions to do something that reached out of .ddev.

For example, 

```yaml
post_install_actions:
-  if [ ${DDEV_PROJECT_TYPE} = "drupal9" ] then echo "some config" > $DDEV_APPROOT/$DDEV_DOCROOT/sites/default/settings.redis.php; fi
- echo "Sample Drupal redis configuration has been placed in sites/default/settings.redis.php if you want to include it from settings.php"
```

Maybe that's worth a try?

**Comment by hussainweb** [comment]
That sounds great. Is there an environment variable that stores the project directory? I don't think it runs in the project directory because I was not able to refer to relative paths in some of the tests. The idea is that I would have a settings.redis.php and just copy the file if it is Drupal.

Alternatively, I could just copy the file to within the `.ddev` directory and then modify the settings.php to include that. Thoughts on this?

**Comment by rfay** [comment]
As in the example. `$DDEV_APPROOT`. See the first set (host-side) of environment variables in https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/#environment-variables-provided

**Comment by rfay** [comment]
I think putting the file in .ddev should be fine. Really I wish settings.ddev.php lived there.

**Comment by rfay** [comment]
The one thing to remember for sure though: Unless this is a drupal-specific recipe, it needs to not do things that other CMSs will find objectionable.

**Comment by hussainweb** [comment]
@rfay, agreed. In fact, I was exploring the idea of creating another addon specific to Drupal. But I think this is a simple enough conditional. I'll also check on how to not even copy the file if the recipe is not Drupal.

That brings me to a question: can I call a shell script directly from post_install_actions? I suppose I can but the question is how do I get a path of a file I am not copying to .ddev directory.

**Comment by rfay** [comment]
Yes, that's exactly what you call there. See https://github.com/drud/ddev-drupal9-solr/blob/fcb7de120f937d818cb58a50c0b56e44cb146732/install.yaml#L12 for example.

**Comment by hussainweb** [comment]
@rfay, can you review [this change](https://github.com/hussainweb/ddev-redis/commit/6159e927b1ee9d35d0ebc2b27cb488983c4bd1d1)?

I eventually copied the file to the settings directory as I couldn't figure out how to get the location of the `.ddev` directory from settings.php. I see `DDEV_APPROOT` environment variable is not listed under the container scripts section and if that is the host path, then we can use it within the container. I couldn't find out another simpler way to determine this. I wanted to avoid the `dirname('../../..')` trick for this because then I would have to factor in the web root.

**Comment by rfay** [comment]
I didn't try it out, but it looks good. Location of .ddev dir (on host) should be `$DDEV_APPROOT/.ddev`. In container, should be `/var/www/html/.ddev`

**Comment by hussainweb** [comment]
Thanks @rfay. I noticed a few problems and so going to move this to a PR.

**Comment by hussainweb** [comment]
@rfay, a question: would you still prefer the redis settings file to be within the `.ddev` directory? Or is it better it gets copied to be in the same directory as `settings.ddev.php`?

**Comment by rfay** [comment]
I'm fine with it either way. Probably since settings.ddev.php has been (wrongly) in sites/default for so many years it's fine to put it in there.

**Comment by joelpittet** [comment]
Thanks for adding the settings, that is a great way to get bootstrapped up. Could it also respect the `disable_settings_management` flag?

**Comment by rfay** [comment]
Wow, @joelpittet - this is a really old issue. Could you please open a new issue and give context for your request? Probably a PR would be fine also.

**Comment by joelpittet** [comment]
@rfay Yes for sure https://github.com/drud/ddev-redis/issues/6

**Comment by rfay** [comment]
This was completed in 
* https://github.com/ddev/ddev-redis/pull/3
